#!/bin/bash
cd /media/chemgen/Elements
PICARD=/media/chemgen/Angiogenesis/EXOME_PIPE/picard/picard.jar
java -jar $PICARD SortVcf \
    I=1000G_omni2.5.hg19.vcf \
    O=1000G_omni2.5_sorted.hg19.vcf \
    SEQUENCE_DICTIONARY=ucsc.hg19.dict
