#!/bin/bash
echo --- running rpkm_dir ---
CONIFER=/home/chemgen/EXOME/conifer/conifer.py
PROBES=/home/chemgen/EXOME/conifer/probes.txt
ANDY_COUNT=1
while [ $ANDY_COUNT -le 9 ]; do
	CUR_DIR=/media/chemgen/Elements/SAI/Output_Andy${ANDY_COUNT}/FIX_Andy${ANDY_COUNT}
	cd ${CUR_DIR}
	mkdir -p ../RPKM_Andy${ANDY_COUNT}
	for f in *.bam; do
		STEM=$(basename "${f}" .marked.realigned.fixed.bam);
		python $CONIFER rpkm \
		--probes $PROBES \
		--input $STEM.marked.realigned.fixed.bam \
		--output ../RPKM_Andy${ANDY_COUNT}/$STEM.rpkm.txt
	done
	ANDY_COUNT=$((ANDY_COUNT=ANDY_COUNT+1))
done
