#!/bin/bash
cd /media/chemgen/Elements/SAK_DHK_RG/fixed
GATK=/media/chemgen/Angiogenesis/EXOME_PIPE/GATK/GenomeAnalysisTK.jar
for f in *.bam; do
    STEM=$(basename "${f}" .bam);
    java -jar $GATK \
    -T PrintReads \
    --BQSR ${STEM}_recal_data.csv \
    -R /media/chemgen/Angiogenesis/EXOME_PIPE/bwa.kit/hg19/hg19.fa \
    -I $f \
    --out ${STEM}.BQSR.bam
done
