#!/bin/bash
cd /media/chemgen/Elements/SAK_DHK_RG/BQSR
GATK=/media/chemgen/Angiogenesis/EXOME_PIPE/GATK/GenomeAnalysisTK.jar
for f in *.BQSR_snps.vcf; do
    STEM=$(basename "${f}" .BQSR_snps.vcf);
    java -jar $GATK \
    -T VariantRecalibrator \
    -R /media/chemgen/Angiogenesis/EXOME_PIPE/bwa.kit/hg19/hg19.fa \
    -input ${f} \
    -resource:hapmap,known=false,training=true,truth=true,prior=15.0 /media/chemgen/Elements/hapmap_3.3_sorted.hg19.vcf \
    -resource:omni,known=false,training=true,truth=false,prior=12.0 /media/chemgen/Elements/1000G_omni2.5_sorted.hg19.vcf \
    -resource:dbsnp,known=true,training=false,truth=false,prior=8.0 /media/chemgen/Elements/dbsnp_138_sorted.hg19.vcf \
    -an QD -an HaplotypeScore -an MQRankSum -an ReadPosRankSum -an FS -an MQ \
    -mode SNP \
    -recalFile ${STEM}_recal_data.csv \
    -tranchesFile ${STEM}.tranches \
    -rscriptFile ${STEM}.plots \
    -U ALLOW_SEQ_DICT_INCOMPATIBILITY    
    
done
